trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'MyDockerHub'
        repository: 'my-chat-server'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/src/MyChatServer/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/src/MyChatServer'
        tags: '$(tag)'
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/src/MyChatServer/Dockerfile'
    #     tags: |
    #       $(tag)
    # - task: Docker@2
    #   displayName: Push an image
    #   inputs:
    #     containerRegistry: 'MyDockerHub'
    #     repository: 'my-chat-server'
    #     command: 'push'
    #     tags: '$(tag)'
