version: "3.8"
name: "my-chat-server"
services:
  api:
    build:
      context: /MyChatServer
      dockerfile: Dockerfile
      target: server-final
    ports:
      - "8080:8080"
    environment:
      - CONNECTION_STRING=Server=db;Database=myChat;User=sa;Password=S3cur3P@ssW0rd!;TrustServerCertificate=Yes;
      - AUTHORIZATION_URL=http://authorization:8080
      - REDIS_URL=redis:6379
    depends_on:
      - db
      - redis
      - authorization

  authorization:
    build:
      context: /MyChatServer
      dockerfile: Dockerfile
      target: authorization-final
    environment:
      - CONNECTION_STRING=Server=db;Database=myChat;User=sa;Password=S3cur3P@ssW0rd!;TrustServerCertificate=Yes;
      - REDIS_URL=redis:6379
    depends_on:
      - db
      - redis

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379" # Redis server port
      - "8001:8001" # RedisInsight port

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - sqlDB:/var/opt/mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "S3cur3P@ssW0rd!"

volumes:
  sqlDB:
